const kulyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kuly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src: './images/kuly_003.jpg',
        name: '[삼양] 불닭볶음면 매운맛 5개입',
        summary: '화끈하게 매운 맛의 중독',
        price: 4180,
        sale: 10,
        review: 245,
    },
    {
        src: './images/kuly_004.jpg',
        name: '[CJ] 고메 함박스테이크',
        summary: '두툼하고 육즙 가득한 한끼',
        price: 6980,
        sale: 15,
        review: 89,
    },
    {
        src: './images/kuly_005.jpg',
        name: '[농심] 새우깡 오리지널 90g',
        summary: '언제 먹어도 맛있는 국민과자',
        price: 1380,
        sale: 5,
        review: 521,
    },
    {
        src: './images/kuly_006.jpg',
        name: '[비비고] 소고기미역국 500g',
        summary: '든든하고 진한 국물 맛',
        price: 3980,
        sale: 8,
        review: 132,
    },
    {
        src: './images/kuly_007.jpg',
        name: '[풀무원] 생가득 얇은피 만두 420g',
        summary: '얇은 피에 꽉 찬 속',
        price: 5480,
        sale: 12,
        review: 310,
    },
    {
        src: './images/kuly_008.jpg',
        name: '[오뚜기] 진라면 순한맛 5입',
        summary: '남녀노소 모두 좋아하는 순한맛',
        price: 3280,
        sale: 9,
        review: 402,
    },
    {
        src: './images/kuly_009.jpg',
        name: '[빙그레] 바나나맛우유 240ml',
        summary: '달콤한 추억의 맛',
        price: 1200,
        sale: 0,
        review: 712,
    },
    {
        src: './images/kuly_010.jpg',
        name: '[서울우유] 나100% 우유 1L',
        summary: '신선한 원유 그대로',
        price: 2600,
        sale: 6,
        review: 198,
    },
    {
        src: './images/kuly_011.jpg',
        name: '[남양] 맛있는 우유 GT 900ml',
        summary: '고소하고 부드러운 풍미',
        price: 2500,
        sale: 5,
        review: 165,
    },
    {
        src: './images/kuly_012.jpg',
        name: '[델몬트] 오렌지 주스 1.5L',
        summary: '비타민 가득 상큼한 한잔',
        price: 3900,
        sale: 11,
        review: 143,
    }
    
]